In [2]:
import numpy as np

In [3]:
my_1d_array = np.array([1,2,3])
type(my_1d_array)

numpy.ndarray

In [5]:
my_1d_array.shape

(3,)

In [6]:
my_1d_array[0] #First element

1

In [7]:
my_1d_array[0:2] #Slicing

array([1, 2])

In [8]:
my_2d_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_2d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
my_2d_array.shape #2 rows, 5 columns

(2, 5)

In [9]:
my_2d_array[0] #First row

array([1, 2, 3, 4, 5])

In [10]:
my_2d_array[1] #Second row

array([ 6,  7,  8,  9, 10])

In [13]:
my_2d_array[0][1] #First row, element 1
my_2d_array[0,1] #Also first row, element 1

2

In [14]:
my_2d_array[0:2,1:3] #Partial array

array([[2, 3],
       [7, 8]])

In [16]:
np.zeros(3) #1D array with 3 zeroes
np.zeros((3,3)) #3x3 array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
#This has a start, stop, step logic

np.arange(10)
np.arange(2,10) #Start at 2, stop at 10
np.arange(2,10,2) #Jumping by 2 at each time

array([2, 4, 6, 8])

In [24]:
np.linspace(1,5,20) #Linspace means linear...evenly spaced between starting and stopping points.

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [25]:
#Numpy has functionality for rounding

float_array = np.linspace(1,5,20)
np.round(float_array,2)#Round to two decimal places

array([1.  , 1.21, 1.42, 1.63, 1.84, 2.05, 2.26, 2.47, 2.68, 2.89, 3.11,
       3.32, 3.53, 3.74, 3.95, 4.16, 4.37, 4.58, 4.79, 5.  ])

In [26]:
np.random.rand(5) #1D with 5 random numbers
        

array([0.82146206, 0.66516466, 0.39968819, 0.93815429, 0.71879101])

In [27]:
np.random.rand(5,2)#2D with 5 rows

array([[0.32110002, 0.12419332],
       [0.93651514, 0.77854409],
       [0.70682798, 0.97532319],
       [0.77732492, 0.75283718],
       [0.99173379, 0.03659898]])

In [28]:
np.random.randint(20,80,100)
#Provided array of 100 random integers that are between 20 and 80

array([71, 45, 20, 46, 42, 29, 67, 70, 45, 74, 69, 65, 59, 48, 58, 45, 54,
       72, 44, 28, 32, 76, 68, 58, 57, 27, 61, 71, 27, 56, 45, 28, 36, 65,
       37, 27, 46, 51, 47, 21, 31, 77, 50, 22, 65, 72, 22, 28, 65, 29, 26,
       76, 72, 41, 29, 37, 64, 50, 64, 31, 74, 57, 51, 36, 37, 51, 63, 60,
       64, 27, 26, 35, 35, 75, 65, 56, 59, 41, 46, 45, 28, 33, 47, 24, 33,
       37, 78, 55, 39, 77, 40, 50, 61, 31, 58, 48, 43, 68, 60, 66])

In [30]:
np.random.randint(20,80,(10,10)) #100 random integers but instead of 1D, 2D that is 10x10

array([[77, 24, 71, 27, 42, 25, 31, 58, 72, 36],
       [58, 65, 79, 54, 78, 50, 53, 25, 54, 20],
       [36, 68, 50, 76, 25, 34, 21, 73, 43, 58],
       [77, 58, 49, 53, 65, 31, 24, 51, 73, 40],
       [62, 70, 76, 51, 41, 73, 48, 31, 29, 74],
       [72, 59, 25, 61, 35, 30, 50, 20, 21, 58],
       [53, 44, 58, 41, 78, 24, 59, 72, 29, 26],
       [54, 70, 68, 41, 58, 77, 59, 53, 41, 34],
       [47, 46, 21, 75, 34, 53, 57, 74, 57, 57],
       [23, 77, 50, 28, 40, 33, 62, 37, 30, 35]])

In [31]:
#You can reshape an array

my_1d_array = np.random.randint(20,80,100)
my_2d_array = my_1d_array.reshape(10,10)
print(my_2d_array)

[[42 30 65 65 39 43 42 73 64 31]
 [34 61 58 59 47 56 36 30 26 60]
 [70 78 76 55 49 78 54 66 52 41]
 [22 35 35 77 41 29 76 77 31 31]
 [79 71 47 52 71 22 40 76 21 36]
 [79 60 78 24 58 69 28 20 52 28]
 [70 20 60 31 73 66 38 77 76 42]
 [66 67 77 27 79 31 23 38 61 45]
 [77 34 25 31 54 50 52 30 79 57]
 [37 68 62 66 43 73 61 33 76 54]]
